steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/wspbotproject/cloudbottest:$SHOR_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/wspbotproject/cloudbottest:$SHOR_SHA']
